version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - /opt/jenkins_home:/var/jenkins_home
    networks:
      - net
  remote_host:
    container_name: remote_host
    image: remote_host
    build:
      context: centos
    networks:
      - net
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    volumes:
      - $PWD/mysql_data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    networks: 
      - net
networks:
  net:
